package com.bf.comm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxmpset<M extends BaseWxmpset<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMpid(java.lang.String mpid) {
		set("mpid", mpid);
	}

	public java.lang.String getMpid() {
		return get("mpid");
	}

	public void setWechatid(java.lang.String wechatid) {
		set("wechatid", wechatid);
	}

	public java.lang.String getWechatid() {
		return get("wechatid");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setTel(java.lang.Integer tel) {
		set("tel", tel);
	}

	public java.lang.Integer getTel() {
		return get("tel");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
