package com.bf.comm.model;

import com.bf.comm.model.base.BaseAdminbg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Adminbg extends BaseAdminbg<Adminbg> {
	public static final Adminbg dao = new Adminbg();
}
