package com.bf.comm.model;

import com.bf.comm.model.base.BaseRecond;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recond extends BaseRecond<Recond> {
	public static final Recond dao = new Recond();
}
