package com.bf.comm.model;

import com.bf.comm.model.base.BaseWxmpset;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wxmpset extends BaseWxmpset<Wxmpset> {
	public static final Wxmpset dao = new Wxmpset();
}
